version: '3.8'

services:
  weather-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - weather_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/weather.db
      - DEBUG=False
    restart: unless-stopped

volumes:
  weather_data: